server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka

spring:
  application:
    name: chat-manager-cloud-config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${GIT_URL:https://github.com/tk4a/chat-manager-configuration}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health