server:
  port: 8888

spring:
  application:
    name: chat-manager-cloud-config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${GIT_URL:https://github.com/tk4a/chat-manager-configuration}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}